wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:title>', views.getentry, name = 'getentry'),
    path("search", views.search, name="search"),
    path("create", views.createentry, name='create'),
    path("wiki/edit/<str:title>", views.editpage, name="edit"),
    path('random', views.randompage, name='random')
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
import markdown2
from django.urls import reverse
from django import forms
from . import util
import random


class NewSearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'search',
        'placeholder' : 'Search Encyclopedia'
    }))

class NewEntryForm(forms.Form):

    topic = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Enter Topic Name',
    }), label='')

    content = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder' : 'Enter Markdown Content Here',
    }), label='')

class EditEntryForm(forms.Form):

    topic = forms.CharField(widget=forms.TextInput, label = '')
    content = forms.CharField(widget=forms.Textarea, label = '')


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        'search_form':  NewSearchForm()
    })

def getentry(request, title):

    if title in util.list_entries():
        mdfile = util.get_entry(title)
        htmlfile = markdown2.markdown(mdfile)
        
        return render(request, 'encyclopedia/wikipage.html', {   
            'htmlfile' : htmlfile,
            'title' : title,
            'search_form' : NewSearchForm()
        })
    
    else:
        return render(request, 'encyclopedia/errorpage.html', {
            'title' : title,
            'search_form' : NewSearchForm()
        })
    


def search(request):

    if request.method == 'POST':
        form = NewSearchForm(request.POST)

        if form.is_valid():
            query = form.cleaned_data['query']
            searchentries = util.get_entry(query)

            if searchentries:
                return redirect(reverse('encyclopedia:getentry', args=[query]))
            
            else:
                related = []

                for entry_name in util.list_entries():
                    if query.lower() in entry_name.lower() or entry_name.lower() in query.lower():
                        related.append(entry_name)

                return render(request, "encyclopedia/searchpage.html", {
                "query": query,
                "related": related,
                "search_form": NewSearchForm()
                })

def createentry(request):

    if request.method == 'POST':
        createform = NewEntryForm(request.POST)

        if createform.is_valid():
        
            topic = createform.cleaned_data['topic']
            content = createform.cleaned_data['content']

            if topic in util.list_entries():
                return render(request, 'encyclopedia/createerror.html', {
                    'topic' : topic,
                    'search_form' : NewSearchForm()
                })
                
            util.save_entry(topic, content)
            return redirect(reverse('encyclopedia:getentry', args=[topic]))
            
    return render(request, 'encyclopedia/newtask.html', {
        'createform' : NewEntryForm()
    })

def editpage(request, title):
    editform = EditEntryForm(request.POST)
    content = util.get_entry(title)

    if request.method == 'POST':

        if content == None:
            return render(request, 'encyclopedia/editerror.html', {
                'title' : title,
                'search_form' : NewSearchForm()
            })

        if editform.is_valid():
            newtopic = editform.cleaned_data['topic']
            newcontent = editform.cleaned_data['content']

            util.save_entry(newtopic, newcontent)
            return redirect(reverse('encyclopedia:getentry', args=[newtopic]))

    if request.method == 'GET':

        return render(request, 'encyclopedia/editpage.html' ,{
            'title' : title,
            'content' : content,
            'search_form' : NewSearchForm(),
            'editform' : EditEntryForm(initial={'topic':title, 'content':content} )
        })
    
def randompage(request):
    
    entries = util.list_entries()
    randNum = random.randrange(0, len(entries)-1)
    randEntry = entries[randNum]

    return redirect(reverse('encyclopedia:getentry', args=[randEntry]))


        

wiki/encyclopedia/templates/encyclopedia/createerror.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    
    <h1>'{{ topic }}' already exists. Try searching for it or create something else!</h1>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/editerror.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    
    <h1>'{{ title }}' does not exist. Try searching for something else or create your own page!</h1>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit Page:</h1>

    <form method="post">
        {% csrf_token %}
        {{ editform }}
        <input type="submit" name="Save" >
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/errorpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    
    <h1>'{{ title }}' was not found. Try searching for something else or create your own page!</h1>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{entry}}" type="">{{entry}}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    {{ search_form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a> 
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newtask.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    <h1>Create New Page:</h1>

    <form method="post">
        {% csrf_token %}
        {{ createform }}
        <input type="submit" name="Save" >
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/searchpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results for "{{query}}":</h1>
    {% if related %}

    <p>Related Entries:</p>

    <ul>
        {% for query in related %}
            <li><a href="wiki/{{query}}" type="">{{query}}</a> </li>
        {% endfor %}
    </ul>

    {% else %}
    <p>No search results found for "{{query}}". Try searching for something else or create your own page!</p>

    {% endif %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/wikipage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    
    {{ htmlfile|safe }}

    <a href="edit/{{title}}"> Edit Page</a>

{% endblock %}